# Generated by Django 4.2.7 on 2026-06-18 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('room_rate_standard', models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(0)])),
                ('room_rate_deluxe', models.FloatField(default=800, validators=[django.core.validators.MinValueValidator(0)])),
                ('room_rate_suite', models.FloatField(default=1500, validators=[django.core.validators.MinValueValidator(0)])),
                ('food_budget', models.FloatField(default=50000, validators=[django.core.validators.MinValueValidator(0)])),
                ('marketing_budget', models.FloatField(default=30000, validators=[django.core.validators.MinValueValidator(0)])),
                ('staff_training_budget', models.FloatField(default=20000, validators=[django.core.validators.MinValueValidator(0)])),
                ('renovation_budget', models.FloatField(default=10000, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_quality_target', models.FloatField(default=7.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='simulation.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='classes.team')),
            ],
            options={
                'db_table': 'decision',
                'ordering': ['-round_number'],
                'unique_together': {('team', 'game', 'round_number')},
            },
        ),
    ]
