# Generated by Django 4.2.7 on 2026-06-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='decision',
            name='dec_game_round_idx',
        ),
        migrations.RemoveIndex(
            model_name='decision',
            name='dec_team_game_round_idx',
        ),
        migrations.RemoveIndex(
            model_name='decision',
            name='dec_game_round_submitted_idx',
        ),
    ]
