# Generated by Django 4.2.7 on 2026-06-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('occupancy_rate_standard', models.FloatField(default=0)),
                ('occupancy_rate_deluxe', models.FloatField(default=0)),
                ('occupancy_rate_suite', models.FloatField(default=0)),
                ('revenue_room', models.FloatField(default=0)),
                ('revenue_food', models.FloatField(default=0)),
                ('revenue_total', models.FloatField(default=0)),
                ('cost_operation', models.FloatField(default=0)),
                ('cost_marketing', models.FloatField(default=0)),
                ('cost_staff', models.FloatField(default=0)),
                ('cost_renovation', models.FloatField(default=0)),
                ('cost_total', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('customer_satisfaction', models.FloatField(default=0)),
                ('market_share', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='simulation.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='classes.team')),
            ],
            options={
                'db_table': 'round_result',
                'ordering': ['round_number'],
                'unique_together': {('team', 'game', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='CumulativeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_played', models.IntegerField(default=0)),
                ('total_revenue', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('total_profit', models.FloatField(default=0)),
                ('avg_satisfaction', models.FloatField(default=0)),
                ('avg_market_share', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_results', to='simulation.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_results', to='classes.team')),
            ],
            options={
                'db_table': 'cumulative_result',
                'ordering': ['-final_score'],
                'unique_together': {('team', 'game')},
            },
        ),
    ]
