# Generated by Django 4.2.7 on 2026-06-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cumulativeresult',
            name='cr_game_rank_idx',
        ),
        migrations.RemoveIndex(
            model_name='cumulativeresult',
            name='cr_game_score_idx',
        ),
        migrations.RemoveIndex(
            model_name='roundresult',
            name='rr_game_round_idx',
        ),
        migrations.RemoveIndex(
            model_name='roundresult',
            name='rr_game_team_round_idx',
        ),
        migrations.RemoveIndex(
            model_name='roundresult',
            name='rr_game_round_score_idx',
        ),
    ]
