# Generated by Django 4.2.7 on 2026-06-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classroom',
            name='cr_teacher_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='classroom',
            name='cr_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='team_classroom_idx',
        ),
    ]
