# Generated by Django 4.2.7 on 2026-06-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('running', '进行中'), ('paused', '暂停'), ('finished', '已结束')], default='draft', max_length=10)),
                ('current_round', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=8)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='classes.classroom')),
            ],
            options={
                'db_table': 'game',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=0)),
                ('market_base_demand', models.FloatField(default=1000)),
                ('seasonal_factor', models.FloatField(default=1.0)),
                ('economic_factor', models.FloatField(default=1.0)),
                ('competition_intensity', models.FloatField(default=0.5)),
                ('cost_inflation_rate', models.FloatField(default=0.02)),
                ('max_room_rate', models.FloatField(default=2000)),
                ('min_room_rate', models.FloatField(default=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simulation.game')),
            ],
            options={
                'db_table': 'game_parameter',
                'unique_together': {('game', 'round_number')},
            },
        ),
    ]
