# Generated by Django 4.2.7 on 2026-06-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='game_classroom_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='game_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameparameter',
            name='gp_game_round_idx',
        ),
    ]
